main:
  - name: home
    url: /en
    weight: 1
  - name: food
    url: /en/food/
    weight: 2
  - name: map
    url: /en/foodmap/
    weight: 3
  - name: gallery
    url: /en/gallery/
    weight: 4
  - name: about
    url: /en/about/
    weight: 7