main:
  - name: accueil
    url: /
    weight: 1
  - name: food
    url: /food/
    weight: 2
  - name: carte
    url: /foodmap/
    weight: 3
  - name: photos
    url: /gallery/
    weight: 4
  - name: à propos
    url: /about/
    weight: 7