main:
  - name: home
    url: /en
    weight: 1
  - name: food
    url: /food/
    weight: 2
  - name: map
    url: /foodmap/
    weight: 3
  - name: travel
    url: /travel/
    weight: 4
  - name: misc
    url: /misc/
    weight: 5
  - name: gallery
    url: /tags/all/
    weight: 6
  - name: about
    url: /about/
    weight: 7